### PR TITLE
GUI: Add unref/unset to most places

### PR DESCRIPTION
**Pull request by jwijenbergh**
This needs new puregotk so dependencies have been updated.

When searching (eva -> ev -> eva -> ev -> eva, etc...) we had a slow, but noticeable in a graph (e.g. https://github.com/parikls/mem_usage_ui) memory increase. I knew this would happen as before we did not do any communication with GTK that values can be destroyed. This patch adds unref or unset to most places that decreases the reference count on these objects (unref does that, unset essentially frees/clears).

In puregotk I could maybe solve this using finalizers (meaning do this automatically when Go garbage collects the object). But finalizers are a bit frowned upon and have unpredictable behaviour.

When to unref/unset objects you can find in the docs for most functions. And also https://liacs.leidenuniv.nl/~stefanovtp/courses/StudentenSeminarium/Papers/OS/IMMG.pdf is an amazing reference

The culprit for the eva->ev->eva leak is because we got a string from a pointer as returned by Gtk and then duped it. puregotk now returns a reference instead for this specific case (g_value_dup_string vs g_value_get_string), and we properly free this value too (as purego copies it into a Go allocated string).

### CODE REVIEW

**Comment by jwijenbergh** [comment]
Before:
image

After:
image

Those peaks after are expected I think due to garbage collection kicking in for go objects

**Comment by jwijenbergh** [comment]
This should be fine

**Review by mrvanes — APPROVED** [review]
The specifics are a little over my head but I generally understand why it's needed and as long as we really don't access any free'd object after Unset(), so go for it!

**Comment by jwijenbergh** [comment]
Thanks for the review!

**Pull request merged**
